version: 0.2

phases:
  install:
    commands:
      - java --version
      - mvn --version
  build:
    commands:
      - sudo mvn clean install
      - echo Build Done
artifacts:
  files:
    - '**/*'
